// ╔══════════════════════════════════════════════════════════════════════════╗
// ║   التوسع الذكي في المقولات — 200 مقولة إضافية (شرق + غرب)             ║
// ║   Smart Quotes Expansion — 200 Additional Quotes (East + West)         ║
// ╚══════════════════════════════════════════════════════════════════════════╝

// ─── الصنف الأول: مقولات الشرق (100 مقولة جديدة) ──────────────────────
export const NEW_EASTERN_QUOTES: string[] = [
  '«إذا لم يزدك العلم خُلُقاً، فقد تزيدك المعرفة شقاءً» — مصطفى السباعي',
  '«القراءة المنهجية هي التي تبني العقل، أما القراءة العشوائية فتمتع العقل ولا تبنيه» — عبد الكريم بكار',
  '«العلم بلا تقوى كالسراج في يد اللص، يزيد صاحبه قدرة على الأذى» — أبو حامد الغزالي',
  '«من يقرأ التاريخ لا يرى الحوادث صدفة، بل يراها قانوناً يسير وفق أسباب ومسببات» — ابن خلدون',
  '«لا تجعل يقينك شكاً، ولا علمك جهلاً، ولا ظنك حقاً» — علي بن أبي طالب',
  '«الفكر لا يحده حدود، والروح لا تحبسها جدران، والكتاب هو السبيل لكليهما» — عباس محمود العقاد',
  '«إن المعرفة ليست تكديساً للمعلومات، بل هي القدرة على استثمار الفكرة في الواقع» — مالك بن نبي',
  '«كلما أدبني الدهر أراني نقص عقلي، وإذا ما ازددت علماً زادني علماً بجهلي» — الشافعي',
  '«الأمة التي تقرأ لا تُهزم، والأمة التي تفكر لا تُستعبد» — محمد الغزالي',
  '«العلم يبني، والجهل يهدم، والحكمة هي التي تختار ما نبني وما نهدم» — أحمد شوقي',
  '«ليس الحكيم الذي يعرف الخير من الشر، بل الحكيم الذي يعرف خير الشرين» — ابن القيم',
  '«العلم هو السلم الذي نصعد به نحو ذواتنا قبل أن نصعد به نحو العالم» — إبراهيم الفقي',
  '«لا قيمة لعلم لا يلامس الروح، ولا معنى لحكمة لا تنعكس في السلوك» — جبران خليل جبران',
  '«إن ما تقرأه يحدد من أنت، وما تكتبه يحدد من ستكون» — ميخائيل نعيمة',
  '«العلم نور يضيء الدروب المظلمة، لكنه يحتاج لعين قادرة على الإبصار» — طه حسين',
  '«الحقيقة المطلقة لا يدركها إلا من تجرد من أهواء نفسه» — مصطفى محمود',
  '«الكلمة ليست مجرد حروف، بل هي طاقة تشعل في القلوب جذوة التغيير» — سيد قطب',
  '«القراءة هي السفر في عقول الرجال دون أن تغادر غرفتك» — علي الطنطاوي',
  '«الفكر العربي يحتاج لمزاوجة بين أصالة الحكمة ومعاصرة العلم» — زكي نجيب محمود',
  '«العقل وعاء يضيق بما يوضع فيه إلا وعاء العلم فإنه يتسع» — نجيب محفوظ',
  '«الحكيم هو من ملك زمام لسانه، والجاهل هو من أطلقه» — إبراهيم اليازجي',
  '«العلم بالشيء هو إدراك ماهيته في عالم الوجود وعالم العقل» — الفارابي',
  '«العلم لا يُنال بالراحة، والحكمة لا تُدرك بالتمني» — ابن رشد',
  '«الناس أربعة: رجل يدري ويدري أنه يدري فذلك عالم فاتبعوه» — الخليل بن أحمد',
  '«الكتاب هو الصديق الذي لا يخونك أبداً إذا أخلصت له» — الجاحظ',
  '«العلم علم القلب، فذاك العلم النافع» — الحسن البصري',
  '«القراءة هي حياة العقل، والكتابة هي تخليد لتلك الحياة» — أبو هلال العسكري',
  '«من طلب العلم لغير الله لم يزدد من الله إلا بعداً» — ابن حزم',
  '«العقل غريزة تقوى بالتجارب وتنمو بالتعلم» — الماوردي',
  '«في كل كتاب تقرأه، أنت تقابل روحاً جديدة تشاركك تجاربها» — مصطفى صادق الرافعي',
  '«الحكمة هي البصيرة التي تفرق بين الثابت والمتحول» — محمد عمارة',
  '«المستعد للشيء يدرك حقيقته بأدنى تنبيه» — ابن سينا',
  '«العلم لا يكتمل إلا بالشك، فبالشك تُعرف الحقائق» — الرازي',
  '«تعلّم حسن الاستماع كما تتعلم حسن الكلام» — ابن المقفع',
  '«الحكمة هي أعلى الفضائل الإنسانية وأقربها للكمال» — الكندي',
  '«الكتابة هي مرآة العصور التي لا تصدأ» — لسان الدين بن الخطيب',
  '«من لم يرتضِ بالعلم دليلاً، تاه في دروب الضلال» — ابن باجة',
  '«تعلموا العلم لتعرفوا الحق، واعرفوا الحق لتعملوا به» — عبد الحميد بن باديس',
  '«الموقف هو الحكمة الحقيقية، والكلمة هي سلاحها» — أمل دنقل',
  '«الحكمة هي صوت الصمت الذي يسبق العاصفة» — بدر شاكر السياب',
  '«في القراءة نجد ما فقدناه في الواقع، وفي الكتابة نصنع ما نتمناه» — محمود درويش',
  '«الذاكرة هي مخزن العلم، والنسيان هو عدوه الأول» — رضوى عاشور',
  '«القراءة هي فعل وجودي يعيد صياغة وعينا بالعالم» — واسيني الأعرج',
  '«الكتب هي أصدقاء الرحلة الذين لا يطلبون شيئاً ويعطون كل شيء» — أحلام مستغانمي',
  '«المعرفة مسؤولية ثقيلة، والحكمة هي القدرة على حملها» — مريد البرغوثي',
  '«الفكر النقدي هو المفتاح الحقيقي لفهم التاريخ» — هشام جعيط',
  '«لا يمكن تجديد العقل إلا من خلال إعادة قراءة التراث بعيون معاصرة» — محمد عابد الجابري',
  '«العلم هو الحرية، والجهل هو العبودية» — قاسم أمين',
  '«الحكيم هو من يبحث عن السؤال لا من يدعي امتلاك الجواب» — توفيق الحكيم',
  '«الأدب هو العلم بصورة فنية، والحكمة هي جوهرهما» — محمد حسين هيكل',
  '«الاستبداد يخشى العلم لأنه يكشف زيفه» — عبد الرحمن الكواكبي',
  '«القوة في العلم، والضعف في الجهل» — جمال الدين الأفغاني',
  '«إصلاح الفكر يبدأ من إصلاح مناهج التعلم» — محمد رشيد رضا',
  '«الفرق بين العالم والجاهل هو الفرق بين البصير والأعمى» — منصور الكيالي',
  '«الحكمة هي البوصلة التي توجه سفينة حياتك في بحر المتناقضات» — نبيل أحمد',
  '«العقل قادر على إدراك الخالق من خلال تأمل مخلوقاته» — ابن طفيل',
  '«العلم شرف لا يملكه إلا من صبر على مرارة طلبه» — أبو الأسود الدؤلي',
  '«أول العلم النية، ثم الاستماع، ثم الفهم، ثم العمل، ثم النشر» — عبد الله بن المبارك',
  '«الوقت هو مادة العلم، فمن أضاع وقته أضاع علمه» — ابن الجوزي',
  '«الحكمة هي معرفة الحق لصوابه، والباطل لفساده» — فخر الدين الرازي',
  '«الوسطية هي قمة الحكمة في الفهم والتطبيق» — يوسف القرضاوي',
  '«الفكر الإنساني نهر متدفق، والكتب هي ضفافه» — أحمد الوائلي',
  '«العلم وسيلة لإعمار الأرض وفق منهج الله» — محمد متولي الشعراوي',
  '«من قرأ كتاباً فكأنما عاش عمراً مع مؤلفه» — أبو حيان التوحيدي',
  '«الحكمة هي الكلمة المختصرة التي تغني عن الكتب الطويلة» — الثعالبي',
  '«العلم زينة للأغنياء ومال للفقراء» — الزمخشري',
  '«الحقيقة مرة، ولكنها الدواء الوحيد للجهل» — البيروني',
  '«من لم يسافر لم يقرأ إلا صفحة واحدة من كتاب الدنيا» — ابن بطوطة',
  '«غاية العلوم نفع الناس وتخفيف آلامهم» — الزهراوي',
  '«المنهج العلمي يبدأ بالشك وينتهي باليقين المبني على التجربة» — الحسن بن الهيثم',
  '«العلم والعدل هما جناحا النهضة» — صلاح الدين الأيوبي',
  '«العلم لا يُعطى إلا لمن أخلص له النية والطلب» — المنصور',
  '«المعرفة ذوق، والحكمة هي حال القلوب المستنيرة» — ابن العربي',
  '«الكتابة لغة العقل الصامتة» — القلقشندي',
  '«العلم شجرة ثمارها الحكمة والعمل الصالح» — ابن عساكر',
  '«الكلمات مفاتيح المعاني، والكتب خزائنها» — الفيروز آبادي',
  '«المجتمع الجاهل يقدس الشخصيات، والمجتمع الواعي يقدس الأفكار» — علي الوردي',
  '«الحكمة تكمن في العودة إلى الفطرة الصافية» — إبراهيم الكوني',
  '«القراءة هي الهروب الجميل من سجن الذات» — غادة السمان',
  '«الكتاب هو الرفيق الذي لا يمل حديثه ولا يتغير وده» — أمين الريحاني',
  '«الفكر المستنير هو الذي يرى النور في آخر النفق» — منصور خالد',
  '«العلم أمانة في عنق صاحبه، والحكمة هي حسن أداء الأمانة» — محمد سليم العوا',
  '«العلم لا يعرف حدوداً، والحكمة هي توظيفه لخدمة البشرية» — أحمد زويل',
  '«المعرفة هي الطريق الوحيد للوصول إلى النجوم» — فاروق الباز',
  '«العلم هو لغة عالمية توحد القلوب قبل العقول» — مجدي يعقوب',
  '«المثقف يجب أن يكون قلقاً دائماً، باحثاً عن الحقيقة لا عن الراحة» — إدوارد سعيد',
  '«الكلمة التي لا تزلزل الأرض تحت أقدام الطغاة هي كلمة ميتة» — نزار قباني',
  '«العلم الحقيقي هو الذي يحرر الإنسان من الخوف» — محمود محمد طه',
  '«القراءة هي السلاح الأقوى لكسر قيود التهميش» — فاطمة المرنيسي',
  '«العلم ليس بكثرة الرواية، وإنما العلم نور يضعه الله في القلب» — مالك بن أنس',
  '«من يطلب الحقيقة بصدق لا يخشى مراجعة أفكاره» — الحسن بن الهيثم',
  '«السعادة القصوى في التأمل العلمي والعمل الحكيم» — ابن باجة',
  '«الحكمة هي الانسجام مع قوانين الطبيعة الكلية» — ابن طفيل',
  '«القارئ الجيد هو من يقرأ ما بين السطور لا الحروف فقط» — عبد الكريم بكار',
  '«الجهل بالدين أخطر من الجهل بالعلم المادي» — محمد الغزالي',
  '«الحياة في سبيل فكرة هي الحياة الحقيقية» — سيد قطب',
  '«الحكيم هو من يرى الفتنة وهي مقبلة، والجاهل يراها وهي مدبرة» — مصطفى السباعي',
  '«العلم والدين وجهان لعملة واحدة هي الحقيقة» — مصطفى محمود',
  '«في حدائق الحكمة، نزرع الأفكار لنجني الأفعال العظيمة» — نبيل أحمد',
  '«المعرفة بلا عمل كالشجر بلا ثمر، والحكمة هي الثمرة المطلوبة» — ابن القيم',
];

// ─── الصنف الثاني: مقولات الغرب (100 مقولة جديدة) ──────────────────────
export const NEW_WESTERN_QUOTES: string[] = [
  '"Be courageous enough to use your own reason." — Immanuel Kant',
  '"He who has a why to live can bear almost any how." — Friedrich Nietzsche',
  '"Reading is thinking with someone else\'s mind instead of your own." — Arthur Schopenhauer',
  '"The unexamined life is not worth living." — Socrates',
  '"The person who reads a lot thinks a lot, and the person who thinks a lot knows the truth." — Plato',
  '"The roots of education are bitter, but the fruit is sweet." — Aristotle',
  '"I think, therefore I am." — René Descartes',
  '"The aim of wisdom is not laughter or weeping, but understanding." — Baruch Spinoza',
  '"It is better to be Socrates dissatisfied than a pig satisfied." — John Stuart Mill',
  '"Custom is the great guide of human life, and wisdom is transcending custom." — David Hume',
  '"The real world of knowledge is the heart, not the mind alone." — Jean-Jacques Rousseau',
  '"I have never had a sorrow that an hour of reading did not relieve." — Montesquieu',
  '"The more I read, the more I realize how little I know." — Voltaire',
  '"Books are ships that pass through the vast seas of time." — Francis Bacon',
  '"Science is knowledge of consequences and dependence on the sequence of facts." — Thomas Hobbes',
  '"Education creates the person, and reading nourishes the soul." — John Locke',
  '"The person who knows everything does not need to read, but he has not been born yet." — Benjamin Franklin',
  '"Information is the currency of democracy, and wisdom is its value." — Thomas Jefferson',
  '"The best thing about books is that they allow us to speak with the dead." — Abraham Lincoln',
  '"Knowledge is acquired by reading, but wisdom is acquired by observation." — Ralph Waldo Emerson',
  '"Read the best books first, or you may not have a chance to read them at all." — Henry David Thoreau',
  '"Good reading is a defense against active ignorance." — Mark Twain',
  '"There is no mountain that cannot be climbed with knowledge, and no ocean that cannot be crossed with a book." — Ernest Hemingway',
  '"Reading is the key that opens the doors to everything." — Victor Hugo',
  '"Knowledge is the only thing that increases by sharing it with others." — Charles Dickens',
  '"Books show us what we are and what we can become." — Oscar Wilde',
  '"Never fear being eccentric in your ideas, for every accepted idea was once eccentric." — Bertrand Russell',
  '"More important than being successful is being of value." — Albert Einstein',
  '"If I have seen further, it is by standing on the shoulders of giants." — Isaac Newton',
  '"Simplicity is the ultimate sophistication." — Leonardo da Vinci',
  '"The book is the greatest human invention because it allows us to exchange ideas across centuries." — Galileo Galilei',
  '"Science is human progress, and wisdom is directing that progress toward good." — Nikola Tesla',
  '"Intelligence is the ability to adapt to change." — Stephen Hawking',
  '"Science is a candle in the dark, and books are its wick." — Carl Sagan',
  '"If you can\'t explain your idea to a six-year-old, you don\'t really understand it." — Richard Feynman',
  '"Nothing in life is to be feared, it is only to be understood." — Marie Curie',
  '"Science is the careful observation and deep analysis of everything around us." — Charles Darwin',
  '"Writing is the release of psychological treasures and purification of the soul." — Sigmund Freud',
  '"You cannot change anything unless you accept it, and knowledge is the first step to acceptance." — Carl Jung',
  '"Knowledge is not centralized, it is distributed among all people." — Friedrich Hayek',
  '"Science is a means of understanding reality, not of changing it by force." — Milton Friedman',
  '"The function of education is to help students learn how to learn for themselves." — Noam Chomsky',
  '"We are drowning in information but starving for wisdom." — Edward O. Wilson',
  '"The real power in this century is the ability to distinguish truth from fiction." — Yuval Noah Harari',
  '"In a time of universal deceit, telling the truth is a revolutionary act." — George Orwell',
  '"Books are the best way to escape reality and the best way to face it." — Aldous Huxley',
  '"A book must be the axe for the frozen sea inside us." — Franz Kafka',
  '"Knowledge without experience is mere information, and wisdom is lived experience." — Paulo Coelho',
  '"Writing is the only way I know not to die completely." — Gabriel García Márquez',
  '"The library is a miniature universe containing all possibilities of human thought." — Jorge Luis Borges',
  '"We are not born wise; we become so through learning and pain." — Simone de Beauvoir',
  '"We are condemned to be free, and knowledge gives that freedom meaning." — Jean-Paul Sartre',
  '"Do not walk behind me for I may not lead. Walk beside me and be my friend in the search for truth." — Albert Camus',
  '"Science is a god for some and a milk cow for others." — Friedrich Schiller',
  '"Those who know nothing of foreign languages know nothing of their own." — Johann Wolfgang von Goethe',
  '"The limits of my language mean the limits of my world." — Ludwig Wittgenstein',
  '"Thinking is beginning to question the obvious." — Martin Heidegger',
  '"Science does not think; it is the human mind that gives science its meaning." — Hannah Arendt',
  '"Knowledge is power, and whoever holds the book holds part of that power." — Michel Foucault',
  '"There is nothing outside the text, and every reading is a rewriting." — Jacques Derrida',
  '"Reading is the act of chasing meanings that never end." — Umberto Eco',
  '"Classics are books that have never finished saying what they have to say." — Italo Calvino',
  '"Memory is resistance against forgetting, and books are the archive of that resistance." — Milan Kundera',
  '"If you only read the books everyone reads, you will think the way everyone thinks." — Haruki Murakami',
  '"Books are a uniquely portable magic." — Stephen King',
  '"Words are our most inexhaustible source of magic, capable of both inflicting harm and healing." — J.K. Rowling',
  '"A library is a place of freedom, where you can explore any world you want." — Neil Gaiman',
  '"The word is the key that opens invisible locks." — Margaret Atwood',
  '"If there is a book you want to read that hasn\'t been written yet, you must write it." — Toni Morrison',
  '"Literature is the last refuge of freedom in totalitarian systems." — Ismail Kadare',
  '"Reading is opening a second eye that sees what others do not." — Orhan Pamuk',
  '"Education is an act of love, and therefore an act of courage." — Paulo Freire',
  '"Institutional learning may kill natural curiosity, so be careful." — Ivan Illich',
  '"The medium is the message, and the book is the greatest medium." — Marshall McLuhan',
  '"The illiterate of the 21st century are not those who cannot read, but those who cannot unlearn." — Alvin Toffler',
  '"Science begins with a problem and ends with deeper and more beautiful problems." — Karl Popper',
  '"Science does not advance in steady steps, but in great intellectual leaps." — Thomas Kuhn',
  '"Science is the poetry of reality." — Richard Dawkins',
  '"Wisdom is the ability to act according to the best available information." — Sam Harris',
  '"We think slowly to learn, and fast to live." — Daniel Kahneman',
  '"Truth is rare and time is precious, so choose what you read carefully." — Yuval Noah Harari',
  '"Knowledge is power, but vulnerability is the door through which wisdom enters." — Brené Brown',
  '"Great leaders do not have the answers; they have the right questions." — Simon Sinek',
  '"Genius is the result of 10,000 hours of learning and practice." — Malcolm Gladwell',
  '"Wisdom is being able to rethink your old convictions." — Adam Grant',
  '"Read what you love until you love reading, then read what builds you." — Naval Ravikant',
  '"Wisdom is knowing what to ignore." — Nassim Taleb',
  '"A book is a conversation with the smartest minds throughout history." — Jordan Peterson',
  '"Philosophy does not give answers; it shatters wrong answers." — Slavoj Žižek',
  '"Good books tell us what we already know but did not have the words to describe." — Alain de Botton',
  '"Reading is an exercise in human empathy." — Martha Nussbaum',
  '"Thought is the space where we test our freedom." — Judith Butler',
  '"The mind is like a parachute; it only works when it is open." — Frank Zappa',
  '"Those not busy being born (continuously learning) are busy dying." — Bob Dylan',
  '"Truth is what we are searching for, and science is our stumbling path toward it." — John Lennon',
  '"There is a crack in everything; that is how the light (knowledge) gets in." — Leonard Cohen',
  '"Knowledge is the only thing that makes you feel younger." — David Bowie',
  '"The only way to get started is to quit talking and begin doing." — Walt Disney',
  '"Innovation distinguishes between a leader and a follower, and knowledge is the fuel of innovation." — Steve Jobs',
  '"It doesn\'t matter how much money you have; what matters is how many ideas and books you have." — Bill Gates',
];
